[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
upload_speed = 921600

[env:native]
platform = native
test_framework = unity
test_ignore = integration/*
lib_deps = 
    throwtheswitch/Unity
build_flags = 
    -I src/core
    -I test/unit/mocks
    -DUNIT_TEST
    -std=gnu++17
build_src_filter = -<*>   ; exclude all src/ files from the normal build

[env:integration]
platform = espressif32
board = nodemcu-32s
framework = arduino
test_ignore = unit/*
monitor_speed = 115200